# This is a basic workflow to help you get started with Actions

name: Continuous Deployment - Dev

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_AUTHTOKEN }}
      run: heroku container:login
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_AUTHTOKEN }}
      run: heroku container:push -a uade-movieapp-g5-api-dev web
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_AUTHTOKEN }}
      run: heroku container:release -a uade-movieapp-g5-api-dev web
